import type { CategoryId, IconTint, Tool } from "./types";

function t(
  slug: string,
  name: string,
  description: string,
  category: CategoryId,
  icon: string,
  iconTint: IconTint,
  keywords: string[],
  extra?: Partial<Tool>,
): Tool {
  return {
    slug,
    name,
    description,
    category,
    href: `/tools/${category}/${slug}`,
    icon,
    iconTint,
    status: "ready",
    keywords,
    ...extra,
  };
}

export const extraTools: Tool[] = [
  t("mortgage-calculator", "Mortgage Calculator", "Home price, down payment, rate and term. Monthly payment and total interest.", "calculators", "Landmark", "blue", ["mortgage", "home loan", "emi house"], { popular: true, badge: "Money", longDescription: "Enter the home price, what you put down, the rate and how many years. You get a monthly payment and how much interest you pay over the life of the loan." }),
  t("gst-calculator", "GST / VAT Calculator", "Add or remove sales tax. Presets for Pakistan, India, UK and a custom rate.", "calculators", "Receipt", "amber", ["gst", "vat", "sales tax", "tax calculator"], { popular: true, badge: "Money" }),
  t("timezone-converter", "Timezone Converter", "Convert a date and time between cities. No live clock API.", "calculators", "Globe", "sky", ["timezone", "pst to ist", "utc converter"], { popular: true, badge: "Time" }),
  t("sleep-calculator", "Sleep Calculator", "Pick a wake time. See bedtimes that land on 90-minute cycles.", "calculators", "Moon", "indigo", ["sleep calculator", "what time should i sleep"], { badge: "Health" }),
  t("pregnancy-due-date", "Pregnancy Due Date", "Estimate a due date from the last period. Screening only, not medical advice.", "calculators", "Baby", "rose", ["due date", "pregnancy calculator", "edd"], { badge: "Health" }),
  t("ovulation-calculator", "Ovulation Calculator", "Estimate a fertile window from cycle length and last period.", "calculators", "HeartPulse", "rose", ["ovulation", "fertile window"], { badge: "Health" }),
  t("tdee-calculator", "TDEE Calculator", "Daily calorie burn from age, size and activity. Same idea as the calorie page, more detail.", "calculators", "Flame", "orange", ["tdee", "maintenance calories"], { badge: "Health" }),
  t("protein-calculator", "Protein Calculator", "A daily protein range from body weight and how hard you train.", "calculators", "Dumbbell", "green", ["protein intake", "grams of protein"], { badge: "Health" }),
  t("water-intake-calculator", "Water Intake Calculator", "A rough daily water target from weight and activity.", "calculators", "Droplets", "sky", ["water intake", "how much water"], { badge: "Health" }),
  t("ideal-weight-calculator", "Ideal Weight Calculator", "Devine and Robinson estimates from height. Not a goal, just a range.", "calculators", "Scale", "purple", ["ideal weight", "healthy weight"], { badge: "Health" }),
  t("compound-interest-calculator", "Compound Interest Calculator", "Principal, rate and years. See the balance grow year by year.", "calculators", "Coins", "amber", ["compound interest", "compound calculator"], { badge: "Money" }),
  t("overtime-calculator", "Overtime Calculator", "Regular hours plus overtime at 1.5x or a custom multiplier.", "calculators", "Clock", "blue", ["overtime pay", "time and a half"], { badge: "Money" }),
  t("pace-calculator", "Pace Calculator", "Finish time, distance or pace. Useful for a run or a walk.", "calculators", "Timer", "teal", ["running pace", "min per km"], { badge: "Health" }),
  t("sip-calculator", "SIP Calculator", "Monthly investing with a yearly return. Future value, not a promise.", "calculators", "PieChart", "green", ["sip calculator", "systematic investment"], { badge: "Money" }),

  t("cgpa-to-percentage", "CGPA to Percentage", "Common 9.5 and 10-point conversions. Your university may use another rule.", "student-tools", "GraduationCap", "green", ["cgpa to percentage", "cgpa convert"], { badge: "Students" }),
  t("percentage-to-gpa", "Percentage to GPA", "Turn a percent into a 4.0 or 10-point GPA. Scales differ by school.", "student-tools", "Percent", "blue", ["percentage to gpa", "marks to gpa"], { badge: "Students" }),

  t("merge-pdf", "Merge PDF", "Combine two or more PDFs into one file.", "file-converters", "Layers", "red", ["merge pdf", "combine pdf", "join pdf"], { popular: true, badge: "Document" }),
  t("split-pdf", "Split PDF", "Keep a page range and download that slice.", "file-converters", "Scissors", "amber", ["split pdf", "extract pdf pages"], { badge: "Document" }),
  t("compress-pdf", "Compress PDF", "Rebuild pages as JPEGs to shrink the file. Text stays readable, photos get softer.", "file-converters", "Minimize2", "rose", ["compress pdf", "reduce pdf size"], { popular: true, badge: "Document" }),
  t("rotate-pdf", "Rotate PDF", "Turn every page 90°, 180° or 270°.", "file-converters", "RotateCw", "sky", ["rotate pdf", "pdf sideways"], { badge: "Document" }),
  t("pdf-to-text", "PDF to Text", "Pull selectable text out of a PDF. Scanned pages need OCR, which this does not do.", "file-converters", "FileType", "slate", ["pdf to text", "extract pdf text"], { badge: "Document" }),
  t("images-to-pdf", "Images to PDF", "Drop JPG or PNG files and get one PDF, one image per page.", "file-converters", "FileImage", "amber", ["images to pdf", "photos to pdf"], { badge: "Document" }),

  t("heic-to-jpg", "HEIC to JPG", "Turn an iPhone HEIC photo into a JPG.", "image-tools", "Image", "red", ["heic to jpg", "heic to jpeg", "iphone photo"], { popular: true, badge: "Images" }),
  t("image-watermark", "Image Watermark", "Stamp text on a photo. Opacity and position are yours to set.", "image-tools", "Stamp", "blue", ["watermark image", "add watermark"], { badge: "Images" }),
  t("passport-photo", "Passport Photo", "Crop a photo to 35×45 mm or 2×2 inch at print size.", "image-tools", "UserCheck", "green", ["passport photo", "visa photo"], { badge: "Images" }),
  t("image-grayscale", "Grayscale Image", "Turn a color photo into black and white.", "image-tools", "Contrast", "slate", ["grayscale", "black and white photo"], { badge: "Images" }),
  t("image-blur", "Blur Image", "Soften a photo. Useful before you share a screenshot.", "image-tools", "Droplets", "sky", ["blur image", "blur photo"], { badge: "Images" }),
  t("image-border", "Image Border", "Add a solid border around a photo.", "image-tools", "AppWindow", "indigo", ["add border to image"], { badge: "Images" }),
  t("og-image-resizer", "OG Image Resizer", "Resize to 1200×630 for social link previews.", "image-tools", "ImageDown", "purple", ["og image", "1200x630", "social preview"], { badge: "Images" }),

  t("mph-to-kmh", "MPH to KM/H", "Convert miles per hour to kilometers per hour.", "unit-converters", "Gauge", "teal", ["mph to kmh", "miles per hour"], { badge: "Units" }),
  t("kmh-to-mph", "KM/H to MPH", "Convert kilometers per hour to miles per hour.", "unit-converters", "Gauge", "teal", ["kmh to mph"], { badge: "Units" }),
  t("stone-to-kg", "Stone to KG", "Convert stone to kilograms.", "unit-converters", "Weight", "green", ["stone to kg"], { badge: "Units" }),
  t("kg-to-stone", "KG to Stone", "Convert kilograms to stone.", "unit-converters", "Weight", "green", ["kg to stone"], { badge: "Units" }),
  t("oz-to-ml", "OZ to ML", "Convert US fluid ounces to milliliters.", "unit-converters", "Droplets", "sky", ["oz to ml", "fl oz"], { badge: "Units" }),
  t("ml-to-oz", "ML to OZ", "Convert milliliters to US fluid ounces.", "unit-converters", "Droplets", "sky", ["ml to oz"], { badge: "Units" }),
  t("psi-to-bar", "PSI to Bar", "Convert pounds per square inch to bar.", "unit-converters", "Gauge", "orange", ["psi to bar", "tire pressure"], { badge: "Units" }),
  t("bar-to-psi", "Bar to PSI", "Convert bar to pounds per square inch.", "unit-converters", "Gauge", "orange", ["bar to psi"], { badge: "Units" }),
  t("watts-to-hp", "Watts to HP", "Convert watts to mechanical horsepower.", "unit-converters", "Flame", "amber", ["watts to hp"], { badge: "Units" }),
  t("hp-to-watts", "HP to Watts", "Convert horsepower to watts.", "unit-converters", "Flame", "amber", ["hp to watts"], { badge: "Units" }),
  t("acres-to-hectares", "Acres to Hectares", "Convert acres to hectares.", "unit-converters", "Ruler", "green", ["acres to hectares"], { badge: "Units" }),
  t("hectares-to-acres", "Hectares to Acres", "Convert hectares to acres.", "unit-converters", "Ruler", "green", ["hectares to acres"], { badge: "Units" }),
  t("cm-to-mm", "CM to MM", "Convert centimeters to millimeters.", "unit-converters", "Ruler", "teal", ["cm to mm"], { badge: "Units" }),
  t("mm-to-cm", "MM to CM", "Convert millimeters to centimeters.", "unit-converters", "Ruler", "teal", ["mm to cm"], { badge: "Units" }),
  t("yards-to-meters", "Yards to Meters", "Convert yards to meters.", "unit-converters", "Ruler", "blue", ["yards to meters"], { badge: "Units" }),
  t("meters-to-yards", "Meters to Yards", "Convert meters to yards.", "unit-converters", "Ruler", "blue", ["meters to yards"], { badge: "Units" }),

  t("remove-extra-spaces", "Remove Extra Spaces", "Collapse repeated spaces and tidy line breaks.", "writing", "AlignLeft", "purple", ["remove extra spaces", "trim whitespace"], { badge: "Writing" }),
  t("find-and-replace", "Find and Replace", "Replace text in a draft. Optional match-case.", "writing", "Search", "blue", ["find and replace", "search replace"], { badge: "Writing" }),
  t("sort-lines", "Sort Lines", "Sort lines A–Z or Z–A. Optional unique.", "writing", "ListFilter", "green", ["sort lines", "alphabetize"], { badge: "Writing" }),
  t("lorem-ipsum", "Lorem Ipsum", "Dummy paragraphs for a layout mockup.", "writing", "Quote", "slate", ["lorem ipsum", "dummy text"], { badge: "Writing" }),
  t("text-compare", "Text Compare", "See which lines differ between two drafts.", "writing", "GitCompare", "indigo", ["diff checker", "compare text"], { popular: true, badge: "Writing" }),
  t("meta-description-counter", "Meta Description Counter", "Count characters for a title and meta description.", "writing", "Tag", "amber", ["meta description", "seo title length"], { badge: "Writing" }),

  t("qr-code-generator", "QR Code Generator", "Type a URL or some text. Download a PNG.", "developer-tools", "QrCode", "indigo", ["qr code", "qr generator", "qr code generator"], { popular: true, badge: "Developers" }),
  t("password-generator", "Password Generator", "Random passwords from your browser’s crypto API.", "developer-tools", "KeyRound", "green", ["password generator", "random password"], { popular: true, badge: "Developers" }),
  t("cron-explainer", "Cron Explainer", "Paste a 5-field cron and read it in English.", "developer-tools", "Clock", "sky", ["cron expression", "cron parser"], { badge: "Developers" }),
  t("htaccess-generator", "htaccess Redirect Generator", "Build a 301 or 302 Apache redirect line.", "developer-tools", "FileCode", "orange", ["htaccess redirect", "301 redirect"], { badge: "Developers" }),
  t("robots-txt-generator", "robots.txt Generator", "Allow or block crawlers and point at a sitemap.", "developer-tools", "FileText", "slate", ["robots.txt", "robots generator"], { badge: "Developers" }),
  t("css-gradient-generator", "CSS Gradient Generator", "Two colors, a direction, and the CSS to copy.", "developer-tools", "Palette", "purple", ["css gradient", "linear gradient"], { badge: "Developers" }),
  t("box-shadow-generator", "Box Shadow Generator", "Offset, blur and color. Copy the CSS.", "developer-tools", "Layers", "blue", ["box shadow", "css shadow"], { badge: "Developers" }),
  t("random-string-generator", "Random String Generator", "Letters, numbers or both. Good for IDs and test data.", "developer-tools", "Hash", "teal", ["random string", "nanoid"], { badge: "Developers" }),
  t("contrast-checker", "Contrast Checker", "Foreground and background. WCAG AA / AAA.", "developer-tools", "Contrast", "indigo", ["contrast checker", "wcag contrast"], { badge: "Developers" }),
  t("number-base-converter", "Binary Hex Decimal", "Convert between binary, octal, decimal and hex.", "developer-tools", "Binary", "sky", ["binary converter", "hex converter", "decimal"], { badge: "Developers" }),
];
