import { categories } from "./categories";
import { extraTools } from "./extra-tools";
import type { CategoryId, Tool } from "./types";

export const tools: Tool[] = [
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Height and weight in. BMI and a range out.",
    longDescription:
      "Enter height and weight. You get a BMI number and the usual WHO-style range. It is a screening figure, not a diagnosis.",
    category: "calculators",
    href: "/tools/calculators/bmi-calculator",
    icon: "Scale",
    iconTint: "purple",
    popular: true,
    status: "ready",
    badge: "Health & Fitness",
    keywords: ["bmi", "body mass index", "weight", "health"],
    faqs: [
      {
        question: "What is a healthy BMI range?",
        answer:
          "A BMI between 18.5 and 24.9 is generally considered a healthy or normal weight range for most adults.",
      },
      {
        question: "Is BMI accurate for everyone?",
        answer:
          "BMI is a useful screening tool, but it does not measure body fat directly. Athletes, older adults, and children may need a different assessment.",
      },
      {
        question: "What are the risks of being overweight or underweight?",
        answer:
          "Both can be linked to health issues. Underweight may signal nutrient gaps, while overweight and obesity can raise the risk of heart disease, diabetes, and joint problems.",
      },
      {
        question: "How often should I check my BMI?",
        answer:
          "Checking every few months is enough for most people, or whenever your weight changes noticeably.",
      },
    ],
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Find your exact age in years, months and days.",
    longDescription:
      "Enter a date of birth to calculate exact age, plus the next birthday countdown.",
    category: "calculators",
    href: "/tools/calculators/age-calculator",
    icon: "Cake",
    iconTint: "blue",
    popular: true,
    status: "ready",
    badge: "Date & Time",
    keywords: ["age", "birthday", "date of birth"],
    faqs: [
      {
        question: "Does this include leap years?",
        answer: "Yes. The calculator uses full calendar dates, so leap days are counted correctly.",
      },
      {
        question: "Can I calculate age on a future or past date?",
        answer: "Yes. Set an optional target date to see age as of that day.",
      },
    ],
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, increase or decrease of values.",
    longDescription:
      "Solve common percentage problems: what is X% of Y, X is what percent of Y, and percent change.",
    category: "calculators",
    href: "/tools/calculators/percentage-calculator",
    icon: "Percent",
    iconTint: "green",
    popular: true,
    status: "ready",
    badge: "Math",
    keywords: ["percent", "percentage", "increase", "decrease"],
    faqs: [
      {
        question: "How do I calculate a percentage increase?",
        answer: "Subtract the old value from the new value, divide by the old value, then multiply by 100.",
      },
    ],
  },
  {
    slug: "discount-calculator",
    name: "Discount Calculator",
    description: "Calculate discounts, savings and final price.",
    longDescription: "Enter the original price and discount percent to see the sale price and how much you save.",
    category: "calculators",
    href: "/tools/calculators/discount-calculator",
    icon: "Tag",
    iconTint: "orange",
    status: "ready",
    badge: "Shopping",
    keywords: ["discount", "sale", "savings", "price"],
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Find the right tip amount for any bill.",
    longDescription: "Split a restaurant bill, choose a tip percent, and see the total per person.",
    category: "calculators",
    href: "/tools/calculators/tip-calculator",
    icon: "Coffee",
    iconTint: "rose",
    status: "ready",
    badge: "Everyday",
    keywords: ["tip", "gratuity", "bill", "split"],
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description: "Calculate monthly payment, interest and total cost.",
    longDescription: "Estimate EMI or monthly loan payments from principal, interest rate, and term.",
    category: "calculators",
    href: "/tools/calculators/loan-calculator",
    icon: "Landmark",
    iconTint: "green",
    status: "ready",
    badge: "Finance",
    keywords: ["loan", "emi", "mortgage", "monthly payment"],
  },
  {
    slug: "interest-calculator",
    name: "Interest Calculator",
    description: "Simple and compound interest calculations.",
    longDescription: "Compare simple and compound interest growth on a principal amount.",
    category: "calculators",
    href: "/tools/calculators/interest-calculator",
    icon: "Coins",
    iconTint: "amber",
    status: "ready",
    badge: "Finance",
    keywords: ["interest", "compound", "simple", "savings"],
  },
  {
    slug: "date-calculator",
    name: "Date Calculator",
    description: "Calculate date difference, add or subtract days.",
    longDescription: "Find the number of days between two dates, or add and subtract days from a date.",
    category: "calculators",
    href: "/tools/calculators/date-calculator",
    icon: "CalendarDays",
    iconTint: "indigo",
    status: "ready",
    badge: "Date & Time",
    keywords: ["date", "days between", "add days"],
  },
  {
    slug: "time-calculator",
    name: "Time Calculator",
    description: "Calculate time duration, add or subtract time.",
    longDescription: "Add or subtract hours, minutes, and seconds, or find the duration between two times.",
    category: "calculators",
    href: "/tools/calculators/time-calculator",
    icon: "Clock",
    iconTint: "sky",
    status: "ready",
    badge: "Date & Time",
    keywords: ["time", "duration", "hours", "minutes"],
  },
  {
    slug: "salary-calculator",
    name: "Salary Calculator",
    description: "Calculate your monthly and yearly salary.",
    longDescription: "Convert hourly, weekly, monthly, or yearly pay into the other salary views.",
    category: "calculators",
    href: "/tools/calculators/salary-calculator",
    icon: "Wallet",
    iconTint: "green",
    status: "ready",
    badge: "Finance",
    keywords: ["salary", "hourly", "annual", "wage"],
  },
  {
    slug: "calorie-calculator",
    name: "Calorie Calculator",
    description: "Find out calories based on weight, height and activity.",
    longDescription:
      "Estimate daily calorie needs using the Mifflin-St Jeor formula and your activity level.",
    category: "calculators",
    href: "/tools/calculators/calorie-calculator",
    icon: "Flame",
    iconTint: "orange",
    status: "ready",
    badge: "Health & Fitness",
    keywords: ["calorie", "tdee", "bmr", "diet"],
    faqs: [
      {
        question: "Is this the same as a BMR calculator?",
        answer:
          "BMR is calories at rest. This tool also applies an activity multiplier so you see estimated daily needs (TDEE).",
      },
    ],
  },
  {
    slug: "average-calculator",
    name: "Average Calculator",
    description: "Calculate the average of multiple numbers.",
    longDescription: "Find the mean of a list of numbers. Add as many values as you need.",
    category: "calculators",
    href: "/tools/calculators/average-calculator",
    icon: "ChartColumn",
    iconTint: "blue",
    status: "ready",
    badge: "Math",
    keywords: ["average", "mean", "numbers"],
  },
  {
    slug: "ratio-calculator",
    name: "Ratio Calculator",
    description: "Find the ratio between numbers.",
    longDescription: "Simplify a ratio or scale it so one side matches a target value.",
    category: "calculators",
    href: "/tools/calculators/ratio-calculator",
    icon: "Equal",
    iconTint: "slate",
    status: "ready",
    badge: "Math",
    keywords: ["ratio", "proportion", "scale"],
  },
  {
    slug: "fraction-calculator",
    name: "Fraction Calculator",
    description: "Add, subtract, multiply and divide fractions.",
    longDescription: "Perform fraction arithmetic and see the simplified result plus a decimal value.",
    category: "calculators",
    href: "/tools/calculators/fraction-calculator",
    icon: "PieChart",
    iconTint: "amber",
    status: "ready",
    badge: "Math",
    keywords: ["fraction", "numerator", "denominator"],
  },
  {
    slug: "gpa-calculator",
    name: "GPA Calculator",
    description: "Calculate your semester GPA from course grades and credits.",
    longDescription:
      "Add each course, letter grade and credit hours to get a credit-weighted semester GPA on the 4.0 scale.",
    category: "student-tools",
    href: "/tools/student-tools/gpa-calculator",
    icon: "GraduationCap",
    iconTint: "green",
    popular: true,
    status: "ready",
    badge: "Students",
    keywords: ["gpa", "grade", "semester", "credits"],
    faqs: [
      {
        question: "How is GPA calculated?",
        answer: "Each letter grade has points (A = 4.0). Multiply by credit hours, add them up, then divide by total credits.",
      },
    ],
  },
  {
    slug: "cgpa-calculator",
    name: "CGPA Calculator",
    description: "Find your cumulative GPA across multiple semesters.",
    longDescription:
      "Enter each semester GPA and its credit load to calculate your overall CGPA.",
    category: "student-tools",
    href: "/tools/student-tools/cgpa-calculator",
    icon: "Layers",
    iconTint: "indigo",
    status: "ready",
    badge: "Students",
    keywords: ["cgpa", "cumulative gpa", "semesters"],
  },
  {
    slug: "attendance-calculator",
    name: "Attendance Calculator",
    description: "Check attendance percentage and how many classes you can miss.",
    longDescription:
      "See your current attendance, whether you meet the required percent, and how many upcoming classes you must attend.",
    category: "student-tools",
    href: "/tools/student-tools/attendance-calculator",
    icon: "UserCheck",
    iconTint: "teal",
    status: "ready",
    badge: "Students",
    keywords: ["attendance", "classes", "75 percent", "bunk"],
  },
  {
    slug: "grade-calculator",
    name: "Grade Calculator",
    description: "Turn assignment scores into an overall percentage and letter grade.",
    longDescription:
      "Add quizzes, homework and exams with points earned and points possible to get your unweighted course grade.",
    category: "student-tools",
    href: "/tools/student-tools/grade-calculator",
    icon: "ClipboardCheck",
    iconTint: "purple",
    status: "ready",
    badge: "Students",
    keywords: ["grade", "score", "letter grade", "points"],
  },
  {
    slug: "marks-percentage-calculator",
    name: "Marks Percentage Calculator",
    description: "Convert obtained marks into an overall percentage.",
    longDescription:
      "Enter obtained and total marks for each subject to calculate subject-wise and overall percentage.",
    category: "student-tools",
    href: "/tools/student-tools/marks-percentage-calculator",
    icon: "Percent",
    iconTint: "green",
    status: "ready",
    badge: "Students",
    keywords: ["marks", "percentage", "subjects", "result"],
  },
  {
    slug: "final-grade-calculator",
    name: "Final Grade Calculator",
    description: "Find the score you need on your final exam.",
    longDescription:
      "Enter your current grade, the final exam weight and the course grade you want. The calculator shows the minimum final score required.",
    category: "student-tools",
    href: "/tools/student-tools/final-grade-calculator",
    icon: "Target",
    iconTint: "orange",
    status: "ready",
    badge: "Students",
    keywords: ["final exam", "needed score", "course grade"],
  },
  {
    slug: "weighted-grade-calculator",
    name: "Weighted Grade Calculator",
    description: "Calculate a course grade when categories have different weights.",
    longDescription:
      "Homework, quizzes, midterms and finals often count differently. Add each category score and weight to get the true course grade.",
    category: "student-tools",
    href: "/tools/student-tools/weighted-grade-calculator",
    icon: "Scale",
    iconTint: "blue",
    status: "ready",
    badge: "Students",
    keywords: ["weighted grade", "category", "syllabus"],
  },
  {
    slug: "exam-countdown",
    name: "Exam Countdown",
    description: "See how many days are left and how much to study each day.",
    longDescription:
      "Set your exam date and remaining study hours to get a countdown plus a daily study target.",
    category: "student-tools",
    href: "/tools/student-tools/exam-countdown",
    icon: "Timer",
    iconTint: "blue",
    status: "ready",
    badge: "Students",
    keywords: ["exam", "countdown", "study"],
  },
  {
    slug: "study-time-calculator",
    name: "Study Time Calculator",
    description: "Plan how many hours and sessions you need before an exam.",
    longDescription:
      "Estimate total study time from chapters and minutes each, then see if your daily hours are enough.",
    category: "student-tools",
    href: "/tools/student-tools/study-time-calculator",
    icon: "BookOpen",
    iconTint: "amber",
    status: "ready",
    badge: "Students",
    keywords: ["study plan", "pomodoro", "chapters", "hours"],
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Set a new width and height, then download the file.",
    longDescription: "Pick a width and height, lock the ratio if you want, then download PNG, JPG or WebP.",
    category: "image-tools",
    href: "/tools/image-tools/image-resizer",
    icon: "Scaling",
    iconTint: "purple",
    popular: true,
    status: "ready",
    badge: "Images",
    keywords: ["resize", "image", "photo", "dimensions"],
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Reduce image file size with a quality slider.",
    category: "image-tools",
    href: "/tools/image-tools/image-compressor",
    icon: "Minimize2",
    iconTint: "green",
    status: "ready",
    badge: "Images",
    keywords: ["compress", "optimize", "reduce size"],
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    description: "Crop a photo by dragging a selection box.",
    category: "image-tools",
    href: "/tools/image-tools/image-cropper",
    icon: "Crop",
    iconTint: "orange",
    status: "ready",
    badge: "Images",
    keywords: ["crop", "cut", "selection"],
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    description: "Convert an image to PNG, JPG or WebP.",
    category: "image-tools",
    href: "/tools/image-tools/image-converter",
    icon: "RefreshCcw",
    iconTint: "blue",
    status: "ready",
    badge: "Images",
    keywords: ["convert image", "png", "jpg", "webp"],
  },
  {
    slug: "jpg-to-png",
    name: "JPG → PNG",
    description: "Convert a JPG photo to a PNG file.",
    category: "image-tools",
    href: "/tools/image-tools/jpg-to-png",
    icon: "FileImage",
    iconTint: "sky",
    status: "ready",
    badge: "Images",
    keywords: ["jpg to png", "jpeg to png"],
  },
  {
    slug: "png-to-jpg",
    name: "PNG → JPG",
    description: "Convert a PNG image to JPG.",
    category: "image-tools",
    href: "/tools/image-tools/png-to-jpg",
    icon: "FileImage",
    iconTint: "amber",
    status: "ready",
    badge: "Images",
    keywords: ["png to jpg", "png to jpeg"],
  },
  {
    slug: "webp-to-jpg",
    name: "WebP → JPG",
    description: "Convert a WebP image to JPG.",
    category: "image-tools",
    href: "/tools/image-tools/webp-to-jpg",
    icon: "FileImage",
    iconTint: "orange",
    status: "ready",
    badge: "Images",
    keywords: ["webp to jpg"],
  },
  {
    slug: "jpg-to-webp",
    name: "JPG → WebP",
    description: "Convert a JPG photo to WebP.",
    category: "image-tools",
    href: "/tools/image-tools/jpg-to-webp",
    icon: "FileImage",
    iconTint: "green",
    status: "ready",
    badge: "Images",
    keywords: ["jpg to webp"],
  },
  {
    slug: "png-to-webp",
    name: "PNG → WebP",
    description: "Convert a PNG image to WebP.",
    category: "image-tools",
    href: "/tools/image-tools/png-to-webp",
    icon: "FileImage",
    iconTint: "teal",
    status: "ready",
    badge: "Images",
    keywords: ["png to webp"],
  },
  {
    slug: "webp-to-png",
    name: "WebP → PNG",
    description: "Convert a WebP image to PNG.",
    category: "image-tools",
    href: "/tools/image-tools/webp-to-png",
    icon: "FileImage",
    iconTint: "indigo",
    status: "ready",
    badge: "Images",
    keywords: ["webp to png"],
  },
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    description: "Encode an image as a Base64 data URL.",
    category: "image-tools",
    href: "/tools/image-tools/image-to-base64",
    icon: "Binary",
    iconTint: "slate",
    status: "ready",
    badge: "Images",
    keywords: ["image to base64", "data url"],
  },
  {
    slug: "base64-to-image",
    name: "Base64 to Image",
    description: "Paste Base64 and download the image.",
    category: "image-tools",
    href: "/tools/image-tools/base64-to-image",
    icon: "Image",
    iconTint: "violet",
    status: "ready",
    badge: "Images",
    keywords: ["base64 to image", "decode image"],
  },
  {
    slug: "image-rotator",
    name: "Image Rotator",
    description: "Rotate an image by 90°, 180°, 270° or a custom angle.",
    category: "image-tools",
    href: "/tools/image-tools/image-rotator",
    icon: "RotateCw",
    iconTint: "blue",
    status: "ready",
    badge: "Images",
    keywords: ["rotate image", "turn photo"],
  },
  {
    slug: "image-flipper",
    name: "Image Flipper",
    description: "Flip an image horizontally or vertically.",
    category: "image-tools",
    href: "/tools/image-tools/image-flipper",
    icon: "FlipHorizontal",
    iconTint: "purple",
    status: "ready",
    badge: "Images",
    keywords: ["flip image", "mirror"],
  },
  {
    slug: "image-metadata-viewer",
    name: "Image Metadata Viewer",
    description: "Inspect dimensions, file size and JPEG camera fields.",
    category: "image-tools",
    href: "/tools/image-tools/image-metadata-viewer",
    icon: "Info",
    iconTint: "sky",
    status: "ready",
    badge: "Images",
    keywords: ["exif", "metadata", "image info"],
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    description: "Create PNG favicons and a favicon.ico from a logo.",
    category: "image-tools",
    href: "/tools/image-tools/favicon-generator",
    icon: "AppWindow",
    iconTint: "amber",
    status: "ready",
    badge: "Images",
    keywords: ["favicon", "ico", "apple touch icon"],
  },
  {
    slug: "image-dimension-checker",
    name: "Image Dimension Checker",
    description: "See width, height, aspect ratio and megapixels.",
    category: "image-tools",
    href: "/tools/image-tools/image-dimension-checker",
    icon: "Ruler",
    iconTint: "green",
    status: "ready",
    badge: "Images",
    keywords: ["image size", "width height", "resolution"],
  },
  {
    slug: "svg-to-png",
    name: "SVG → PNG",
    description: "Convert an SVG graphic to a PNG image.",
    category: "image-tools",
    href: "/tools/image-tools/svg-to-png",
    icon: "ImageDown",
    iconTint: "violet",
    status: "ready",
    badge: "Images",
    keywords: ["svg to png", "vector to png"],
    longDescription: "Turn an SVG into a PNG so you can drop it where SVG is not accepted.",
    faqs: [
      { question: "Does this upload my SVG?", answer: "No. The graphic is drawn on a canvas here." },
      { question: "Will fonts and filters look the same?", answer: "Browser-supported SVG features are kept. External fonts or remote images may not load." },
    ],
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Pretty-print, check or minify JSON.",
    category: "developer-tools",
    href: "/tools/developer-tools/json-formatter",
    icon: "Braces",
    iconTint: "indigo",
    popular: true,
    status: "ready",
    badge: "Developers",
    keywords: ["json", "pretty print", "format", "validate", "minify"],
    longDescription: "Paste JSON to pretty-print or minify it. Bad JSON shows the first error.",
    faqs: [
      { question: "Is my JSON uploaded?", answer: "No. Formatting happens in this tab." },
      { question: "Can I minify JSON too?", answer: "Yes. Use Minify to remove extra whitespace." },
    ],
  },
  {
    slug: "json-to-csv",
    name: "JSON → CSV",
    description: "Turn a JSON array of objects into a CSV file.",
    category: "data-tools",
    href: "/tools/data-tools/json-to-csv",
    icon: "FileSpreadsheet",
    iconTint: "green",
    status: "ready",
    badge: "Data",
    keywords: ["json to csv", "export csv"],
    longDescription: "Convert an array of JSON objects into comma-separated rows. Nested objects are stringified so you can open the file in a spreadsheet.",
    faqs: [
      { question: "What JSON shape works best?", answer: "An array of objects with the same keys, such as [{name, score}, …]." },
    ],
  },
  {
    slug: "csv-to-json",
    name: "CSV → JSON",
    description: "Convert CSV rows into a JSON array.",
    category: "data-tools",
    href: "/tools/data-tools/csv-to-json",
    icon: "FileSpreadsheet",
    iconTint: "amber",
    status: "ready",
    badge: "Data",
    keywords: ["csv to json", "parse csv"],
    longDescription: "Parse CSV text, including quoted commas, and download a JSON array. The first row is treated as headers.",
  },
  {
    slug: "xml-to-json",
    name: "XML → JSON",
    description: "Convert XML into a JSON object tree.",
    category: "data-tools",
    href: "/tools/data-tools/xml-to-json",
    icon: "FileCode",
    iconTint: "orange",
    status: "ready",
    badge: "Data",
    keywords: ["xml to json", "parse xml"],
    longDescription: "Turn XML elements, attributes and text into JSON. Repeated tags become arrays.",
  },
  {
    slug: "xml-formatter",
    name: "XML Formatter",
    description: "Pretty-print XML with readable indentation.",
    category: "data-tools",
    href: "/tools/data-tools/xml-formatter",
    icon: "FileCode",
    iconTint: "sky",
    status: "ready",
    badge: "Data",
    keywords: ["xml formatter", "pretty xml"],
  },
  {
    slug: "yaml-to-json",
    name: "YAML → JSON",
    description: "Convert YAML documents to JSON.",
    category: "data-tools",
    href: "/tools/data-tools/yaml-to-json",
    icon: "FileType",
    iconTint: "teal",
    status: "ready",
    badge: "Data",
    keywords: ["yaml to json", "yml"],
  },
  {
    slug: "json-to-yaml",
    name: "JSON → YAML",
    description: "Convert JSON objects to YAML.",
    category: "data-tools",
    href: "/tools/data-tools/json-to-yaml",
    icon: "FileType",
    iconTint: "indigo",
    status: "ready",
    badge: "Data",
    keywords: ["json to yaml", "yml"],
  },
  {
    slug: "base64-encoder",
    name: "Base64 Encoder",
    description: "Turn text into a Base64 string.",
    category: "developer-tools",
    href: "/tools/developer-tools/base64-encoder",
    icon: "Binary",
    iconTint: "sky",
    status: "ready",
    badge: "Developers",
    keywords: ["base64", "encode"],
    longDescription: "Encode Unicode text to Base64. Nothing is uploaded.",
  },
  {
    slug: "base64-decoder",
    name: "Base64 Decoder",
    description: "Decode a Base64 string back to text.",
    category: "developer-tools",
    href: "/tools/developer-tools/base64-decoder",
    icon: "Binary",
    iconTint: "indigo",
    status: "ready",
    badge: "Developers",
    keywords: ["base64 decode", "decode base64"],
  },
  {
    slug: "url-encoder",
    name: "URL Encoder",
    description: "Percent-encode a URL or query string.",
    category: "developer-tools",
    href: "/tools/developer-tools/url-encoder",
    icon: "Link2",
    iconTint: "blue",
    status: "ready",
    badge: "Developers",
    keywords: ["url encode", "percent encode"],
  },
  {
    slug: "url-decoder",
    name: "URL Decoder",
    description: "Decode a percent-encoded URL string.",
    category: "developer-tools",
    href: "/tools/developer-tools/url-decoder",
    icon: "Link2",
    iconTint: "sky",
    status: "ready",
    badge: "Developers",
    keywords: ["url decode", "decode uri"],
  },
  {
    slug: "html-entity-encoder",
    name: "HTML Entity Encoder/Decoder",
    description: "Escape or unescape HTML entities.",
    category: "developer-tools",
    href: "/tools/developer-tools/html-entity-encoder",
    icon: "Code2",
    iconTint: "purple",
    status: "ready",
    badge: "Developers",
    keywords: ["html entities", "escape html", "&amp;"],
  },
  {
    slug: "unix-timestamp",
    name: "Unix Timestamp Converter",
    description: "Convert Unix time to a readable date and back.",
    category: "developer-tools",
    href: "/tools/developer-tools/unix-timestamp",
    icon: "Timer",
    iconTint: "amber",
    status: "ready",
    badge: "Developers",
    keywords: ["unix timestamp", "epoch", "utc"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUID v4 values.",
    category: "developer-tools",
    href: "/tools/developer-tools/uuid-generator",
    icon: "Fingerprint",
    iconTint: "green",
    status: "ready",
    badge: "Developers",
    keywords: ["uuid", "guid", "random id"],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Create SHA-1, SHA-256, SHA-384 or SHA-512 hashes.",
    category: "developer-tools",
    href: "/tools/developer-tools/hash-generator",
    icon: "KeyRound",
    iconTint: "rose",
    status: "ready",
    badge: "Developers",
    keywords: ["hash", "sha256", "checksum"],
    longDescription: "Hash text with the Web Crypto API. Fine for checksums. Do not treat this page as password-storage advice.",
  },
  {
    slug: "json-validator",
    name: "JSON Validator",
    description: "Check whether a JSON string is valid.",
    category: "developer-tools",
    href: "/tools/developer-tools/json-validator",
    icon: "CheckCheck",
    iconTint: "green",
    status: "ready",
    badge: "Developers",
    keywords: ["json validator", "validate json"],
  },
  {
    slug: "json-minifier",
    name: "JSON Minifier",
    description: "Remove extra whitespace from JSON.",
    category: "developer-tools",
    href: "/tools/developer-tools/json-minifier",
    icon: "Minimize2",
    iconTint: "slate",
    status: "ready",
    badge: "Developers",
    keywords: ["json minify", "compress json"],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test a regular expression against sample text.",
    category: "developer-tools",
    href: "/tools/developer-tools/regex-tester",
    icon: "Search",
    iconTint: "purple",
    status: "ready",
    badge: "Developers",
    keywords: ["regex", "regular expression", "match"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Read a JWT header and payload without verifying the signature.",
    category: "developer-tools",
    href: "/tools/developer-tools/jwt-decoder",
    icon: "KeyRound",
    iconTint: "amber",
    status: "ready",
    badge: "Developers",
    keywords: ["jwt decode", "json web token"],
    longDescription: "Read a JWT header and payload. It does not verify the signature or mint tokens.",
  },
  {
    slug: "html-formatter",
    name: "HTML Formatter",
    description: "Pretty-print HTML with readable indentation.",
    category: "developer-tools",
    href: "/tools/developer-tools/html-formatter",
    icon: "FileCode",
    iconTint: "orange",
    status: "ready",
    badge: "Developers",
    keywords: ["html formatter", "pretty html"],
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier",
    description: "Minify CSS by removing comments and extra spaces.",
    category: "developer-tools",
    href: "/tools/developer-tools/css-minifier",
    icon: "Palette",
    iconTint: "rose",
    status: "ready",
    badge: "Developers",
    keywords: ["css minify", "compress css"],
  },
  {
    slug: "js-minifier",
    name: "JS Minifier",
    description: "Strip comments and extra space from JavaScript.",
    category: "developer-tools",
    href: "/tools/developer-tools/js-minifier",
    icon: "FileCode",
    iconTint: "indigo",
    status: "ready",
    badge: "Developers",
    keywords: ["js minify", "javascript minify", "terser"],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Pretty-print SQL queries.",
    category: "developer-tools",
    href: "/tools/developer-tools/sql-formatter",
    icon: "Database",
    iconTint: "teal",
    status: "ready",
    badge: "Developers",
    keywords: ["sql formatter", "pretty sql"],
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB and HSL.",
    category: "developer-tools",
    href: "/tools/developer-tools/color-converter",
    icon: "Palette",
    iconTint: "violet",
    status: "ready",
    badge: "Developers",
    keywords: ["hex to rgb", "rgb to hsl", "color picker"],
  },
  {
    slug: "markdown-to-html",
    name: "Markdown → HTML",
    description: "Turn Markdown into HTML.",
    category: "developer-tools",
    href: "/tools/developer-tools/markdown-to-html",
    icon: "FileText",
    iconTint: "blue",
    status: "ready",
    badge: "Developers",
    keywords: ["markdown to html", "md to html"],
  },
  {
    slug: "length-converter",
    name: "Length Converter",
    description: "Convert meters, feet, inches, miles and more.",
    category: "unit-converters",
    href: "/tools/unit-converters/length-converter",
    icon: "Ruler",
    iconTint: "teal",
    status: "ready",
    keywords: ["length", "meter", "feet", "inch"],
  },
  {
    slug: "weight-converter",
    name: "Weight Converter",
    description: "Convert kilograms, pounds, ounces and grams.",
    category: "unit-converters",
    href: "/tools/unit-converters/weight-converter",
    icon: "Weight",
    iconTint: "green",
    status: "ready",
    keywords: ["weight", "kg", "lb", "pound"],
  },
  {
    slug: "temperature-converter",
    name: "Temperature Converter",
    description: "Convert Celsius, Fahrenheit and Kelvin.",
    category: "unit-converters",
    href: "/tools/unit-converters/temperature-converter",
    icon: "Thermometer",
    iconTint: "orange",
    status: "ready",
    keywords: ["temperature", "celsius", "fahrenheit"],
  },
  {
    slug: "kg-to-lbs",
    name: "KG → LBS",
    description: "Convert kilograms to pounds.",
    category: "unit-converters",
    href: "/tools/unit-converters/kg-to-lbs",
    icon: "Weight",
    iconTint: "green",
    popular: true,
    status: "ready",
    badge: "Units",
    keywords: ["kg to lbs", "kilograms to pounds"],
    longDescription: "Convert kilograms to pounds using 1 kg = 2.2046226218 lb.",
  },
  {
    slug: "lbs-to-kg",
    name: "LBS → KG",
    description: "Convert pounds to kilograms.",
    category: "unit-converters",
    href: "/tools/unit-converters/lbs-to-kg",
    icon: "Weight",
    iconTint: "teal",
    status: "ready",
    badge: "Units",
    keywords: ["lbs to kg", "pounds to kilograms"],
  },
  {
    slug: "cm-to-inches",
    name: "CM → Inches",
    description: "Convert centimeters to inches.",
    category: "unit-converters",
    href: "/tools/unit-converters/cm-to-inches",
    icon: "Ruler",
    iconTint: "blue",
    status: "ready",
    badge: "Units",
    keywords: ["cm to inches", "centimeters to inches"],
  },
  {
    slug: "cm-to-feet",
    name: "CM → Feet",
    description: "Convert centimeters to feet.",
    category: "unit-converters",
    href: "/tools/unit-converters/cm-to-feet",
    icon: "Ruler",
    iconTint: "sky",
    status: "ready",
    badge: "Units",
    keywords: ["cm to feet", "centimeters to feet"],
  },
  {
    slug: "feet-to-cm",
    name: "Feet → CM",
    description: "Convert feet to centimeters.",
    category: "unit-converters",
    href: "/tools/unit-converters/feet-to-cm",
    icon: "Ruler",
    iconTint: "indigo",
    status: "ready",
    badge: "Units",
    keywords: ["feet to cm", "ft to cm"],
  },
  {
    slug: "km-to-miles",
    name: "KM → Miles",
    description: "Convert kilometers to miles.",
    category: "unit-converters",
    href: "/tools/unit-converters/km-to-miles",
    icon: "Ruler",
    iconTint: "amber",
    status: "ready",
    badge: "Units",
    keywords: ["km to miles", "kilometers to miles"],
  },
  {
    slug: "miles-to-km",
    name: "Miles → KM",
    description: "Convert miles to kilometers.",
    category: "unit-converters",
    href: "/tools/unit-converters/miles-to-km",
    icon: "Ruler",
    iconTint: "orange",
    status: "ready",
    badge: "Units",
    keywords: ["miles to km", "miles to kilometers"],
  },
  {
    slug: "celsius-to-fahrenheit",
    name: "Celsius → Fahrenheit",
    description: "Convert °C to °F.",
    category: "unit-converters",
    href: "/tools/unit-converters/celsius-to-fahrenheit",
    icon: "Thermometer",
    iconTint: "rose",
    status: "ready",
    badge: "Units",
    keywords: ["celsius to fahrenheit", "c to f"],
  },
  {
    slug: "fahrenheit-to-celsius",
    name: "Fahrenheit → Celsius",
    description: "Convert °F to °C.",
    category: "unit-converters",
    href: "/tools/unit-converters/fahrenheit-to-celsius",
    icon: "Thermometer",
    iconTint: "red",
    status: "ready",
    badge: "Units",
    keywords: ["fahrenheit to celsius", "f to c"],
  },
  {
    slug: "meters-to-feet",
    name: "Meters → Feet",
    description: "Convert meters to feet.",
    category: "unit-converters",
    href: "/tools/unit-converters/meters-to-feet",
    icon: "Ruler",
    iconTint: "purple",
    status: "ready",
    badge: "Units",
    keywords: ["meters to feet", "m to ft"],
  },
  {
    slug: "liters-to-gallons",
    name: "Liters → Gallons",
    description: "Convert liters to US gallons.",
    category: "unit-converters",
    href: "/tools/unit-converters/liters-to-gallons",
    icon: "Droplets",
    iconTint: "sky",
    status: "ready",
    badge: "Units",
    keywords: ["liters to gallons", "l to gal"],
    longDescription: "Convert liters to US liquid gallons. 1 US gallon is 3.785411784 liters.",
  },
  {
    slug: "inches-to-cm",
    name: "Inches → CM",
    description: "Convert inches to centimeters.",
    category: "unit-converters",
    href: "/tools/unit-converters/inches-to-cm",
    icon: "Ruler",
    iconTint: "green",
    status: "ready",
    badge: "Units",
    keywords: ["inches to cm", "in to cm"],
  },
  {
    slug: "mb-to-gb",
    name: "MB → GB",
    description: "Convert megabytes to gigabytes.",
    category: "unit-converters",
    href: "/tools/unit-converters/mb-to-gb",
    icon: "HardDrive",
    iconTint: "slate",
    status: "ready",
    badge: "Units",
    keywords: ["mb to gb", "megabytes to gigabytes"],
  },
  {
    slug: "gb-to-mb",
    name: "GB → MB",
    description: "Convert gigabytes to megabytes.",
    category: "unit-converters",
    href: "/tools/unit-converters/gb-to-mb",
    icon: "HardDrive",
    iconTint: "indigo",
    status: "ready",
    badge: "Units",
    keywords: ["gb to mb", "gigabytes to megabytes"],
  },
  {
    slug: "bytes-converter",
    name: "Bytes → KB → MB → GB",
    description: "Convert between bytes, kilobytes, megabytes and gigabytes.",
    category: "unit-converters",
    href: "/tools/unit-converters/bytes-converter",
    icon: "HardDrive",
    iconTint: "violet",
    status: "ready",
    badge: "Units",
    keywords: ["bytes to kb", "kb to mb", "mb to gb", "file size converter"],
    longDescription: "See a value as bytes, KB, MB and GB at once. Switch between 1024 (binary) and 1000 (decimal) sizing.",
  },
  {
    slug: "paraphrasing-tool",
    name: "Paraphrasing Tool",
    description: "Rewrite your own draft in Standard, Simple, Formal, Academic, Professional or Creative style.",
    longDescription:
      "Paste a draft you wrote, pick a style, then edit the suggestion so it still sounds like you. Do not use this to hide copied work.",
    category: "writing",
    href: "/tools/writing/paraphrasing-tool",
    icon: "Sparkles",
    iconTint: "green",
    popular: true,
    status: "ready",
    badge: "Writing",
    keywords: ["paraphrase", "rewrite", "reword", "editing"],
    faqs: [
      {
        question: "Can I use this to avoid plagiarism?",
        answer:
          "No. Rewriting someone else’s work and submitting it as your own is still plagiarism. Use the tool to clarify drafts you wrote, then cite any sources you relied on.",
      },
      {
        question: "Does my text leave the browser?",
        answer: "These writing tools run on your device. Nothing is uploaded to a server for rewriting.",
      },
      {
        question: "What do the styles change?",
        answer:
          "Standard keeps a balanced tone. Simple shortens wording. Formal and Academic expand contractions and use more precise verbs. Professional is concise. Creative varies word choice.",
      },
    ],
  },
  {
    slug: "sentence-rewriter",
    name: "Sentence Rewriter",
    description: "Rewrite individual sentences in a clearer style.",
    category: "writing",
    href: "/tools/writing/sentence-rewriter",
    icon: "PenLine",
    iconTint: "purple",
    status: "ready",
    badge: "Writing",
    keywords: ["sentence rewriter", "reword sentence"],
  },
  {
    slug: "paragraph-rewriter",
    name: "Paragraph Rewriter",
    description: "Rewrite each paragraph while keeping the document structure.",
    category: "writing",
    href: "/tools/writing/paragraph-rewriter",
    icon: "AlignLeft",
    iconTint: "indigo",
    status: "ready",
    badge: "Writing",
    keywords: ["paragraph rewriter", "rewrite paragraph"],
  },
  {
    slug: "text-rewriter",
    name: "Text Rewriter",
    description: "Rewrite a full passage without changing the core meaning.",
    category: "writing",
    href: "/tools/writing/text-rewriter",
    icon: "Type",
    iconTint: "blue",
    status: "ready",
    badge: "Writing",
    keywords: ["text rewriter", "reword text"],
  },
  {
    slug: "grammar-checker",
    name: "Grammar Checker",
    description: "Catch common typos, spacing issues and repeated words.",
    category: "writing",
    href: "/tools/writing/grammar-checker",
    icon: "CheckCheck",
    iconTint: "green",
    status: "ready",
    badge: "Writing",
    keywords: ["grammar", "proofread", "spelling"],
  },
  {
    slug: "sentence-simplifier",
    name: "Sentence Simplifier",
    description: "Turn long or dense sentences into easier wording.",
    category: "writing",
    href: "/tools/writing/sentence-simplifier",
    icon: "Minimize2",
    iconTint: "teal",
    status: "ready",
    badge: "Writing",
    keywords: ["simplify", "plain language", "easy english"],
  },
  {
    slug: "text-improver",
    name: "Text Improver",
    description: "Tighten wording and clean up frequent mistakes.",
    category: "writing",
    href: "/tools/writing/text-improver",
    icon: "Wand2",
    iconTint: "violet",
    status: "ready",
    badge: "Writing",
    keywords: ["improve writing", "clarity", "edit"],
  },
  {
    slug: "formal-writing-converter",
    name: "Formal Writing Converter",
    description: "Convert casual notes into more formal language.",
    category: "writing",
    href: "/tools/writing/formal-writing-converter",
    icon: "Briefcase",
    iconTint: "slate",
    status: "ready",
    badge: "Writing",
    keywords: ["formal writing", "professional tone"],
  },
  {
    slug: "active-to-passive",
    name: "Active → Passive Voice",
    description: "Convert simple active sentences into passive voice.",
    category: "writing",
    href: "/tools/writing/active-to-passive",
    icon: "ArrowLeftRight",
    iconTint: "sky",
    status: "ready",
    badge: "Writing",
    keywords: ["passive voice", "active to passive"],
  },
  {
    slug: "passive-to-active",
    name: "Passive → Active Voice",
    description: "Convert simple passive sentences into active voice.",
    category: "writing",
    href: "/tools/writing/passive-to-active",
    icon: "RefreshCcw",
    iconTint: "orange",
    status: "ready",
    badge: "Writing",
    keywords: ["active voice", "passive to active"],
  },
  {
    slug: "summarizer",
    name: "Summarizer",
    description: "Pull the most informative sentences from a longer draft.",
    longDescription:
      "Create a short extractive summary of text you have the right to use. It is a reading aid, not a replacement for citing the original source.",
    category: "writing",
    href: "/tools/writing/summarizer",
    icon: "List",
    iconTint: "amber",
    status: "ready",
    badge: "Writing",
    keywords: ["summarize", "summary", "tldr"],
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences and reading time.",
    category: "writing",
    href: "/tools/writing/word-counter",
    icon: "WholeWord",
    iconTint: "teal",
    status: "ready",
    badge: "Writing",
    keywords: ["word count", "characters", "reading time"],
  },
  {
    slug: "character-counter",
    name: "Character Counter",
    description: "Count characters with and without spaces.",
    category: "writing",
    href: "/tools/writing/character-counter",
    icon: "Hash",
    iconTint: "indigo",
    status: "ready",
    badge: "Writing",
    keywords: ["character count", "letters", "limit"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Switch text to sentence, title, upper or lower case.",
    category: "writing",
    href: "/tools/writing/case-converter",
    icon: "CaseSensitive",
    iconTint: "blue",
    status: "ready",
    badge: "Writing",
    keywords: ["uppercase", "lowercase", "title case"],
  },
  {
    slug: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    description: "Keep the first copy of each repeated line.",
    category: "writing",
    href: "/tools/writing/remove-duplicate-lines",
    icon: "ListFilter",
    iconTint: "rose",
    status: "ready",
    badge: "Writing",
    keywords: ["duplicate lines", "unique lines", "dedupe"],
  },
  {
    slug: "text-reverser",
    name: "Text Reverser",
    description: "Reverse characters, words or lines.",
    category: "writing",
    href: "/tools/writing/text-reverser",
    icon: "FlipHorizontal",
    iconTint: "purple",
    status: "ready",
    badge: "Writing",
    keywords: ["reverse text", "backwards"],
  },
  {
    slug: "readability-checker",
    name: "Readability Checker",
    description: "Estimate reading ease and grade level.",
    category: "writing",
    href: "/tools/writing/readability-checker",
    icon: "BookOpen",
    iconTint: "green",
    status: "ready",
    badge: "Writing",
    keywords: ["readability", "flesch", "grade level"],
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF → JPG",
    description: "Turn each PDF page into a JPG.",
    category: "file-converters",
    href: "/tools/file-converters/pdf-to-jpg",
    icon: "FileImage",
    iconTint: "red",
    popular: true,
    status: "ready",
    badge: "Document",
    keywords: ["pdf to jpg", "pdf to jpeg", "pdf image"],
    longDescription: "Each PDF page becomes a JPG. You download them one by one. Scanned and text PDFs both work.",
    faqs: [
      { question: "Is the PDF uploaded?", answer: "No. Pages are drawn on a canvas here." },
      { question: "How many pages can I convert?", answer: "Keep the file under 20 MB. Very large or complex PDFs may take longer." },
    ],
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG → PDF",
    description: "Combine JPG or PNG images into a PDF.",
    category: "file-converters",
    href: "/tools/file-converters/jpg-to-pdf",
    icon: "FileDown",
    iconTint: "amber",
    status: "ready",
    badge: "Document",
    keywords: ["jpg to pdf", "image to pdf", "png to pdf"],
    longDescription: "Turn one or more JPG or PNG photos into a PDF, one image per page. The file is built locally.",
  },
  {
    slug: "word-to-pdf",
    name: "Word → PDF",
    description: "Convert a DOCX file to a simple text PDF.",
    category: "file-converters",
    href: "/tools/file-converters/word-to-pdf",
    icon: "FileText",
    iconTint: "blue",
    status: "ready",
    badge: "Document",
    keywords: ["word to pdf", "docx to pdf"],
    longDescription: "Extract text from a .docx file and wrap it into a PDF. Complex layout, images and custom fonts are not preserved.",
    faqs: [
      { question: "Does this keep Word formatting?", answer: "No. It is a text-based conversion so you can read the content as a PDF." },
      { question: "Can I upload an old .doc file?", answer: "Use a .docx file. Classic .doc will not open here." },
    ],
  },
  {
    slug: "pdf-to-word",
    name: "PDF → Word",
    description: "Extract PDF text into a Word-compatible file.",
    category: "file-converters",
    href: "/tools/file-converters/pdf-to-word",
    icon: "FileText",
    iconTint: "sky",
    status: "ready",
    badge: "Document",
    keywords: ["pdf to word", "pdf to docx", "extract pdf text"],
    longDescription: "Pull readable text from a PDF and download a Word-compatible .doc. Scanned pages without text need OCR, which this tool does not do.",
    faqs: [
      { question: "Will layout and images survive?", answer: "No. This extracts text only so you can edit the words in Word or Google Docs." },
    ],
  },
  {
    slug: "txt-to-pdf",
    name: "TXT → PDF",
    description: "Turn plain text into a printable PDF.",
    category: "file-converters",
    href: "/tools/file-converters/txt-to-pdf",
    icon: "FileType",
    iconTint: "slate",
    status: "ready",
    badge: "Document",
    keywords: ["txt to pdf", "text to pdf", "notes pdf"],
    longDescription: "Paste text or load a .txt file and download a simple letter-size PDF.",
  },
  {
    slug: "video-compressor",
    name: "Video Compressor",
    description: "Shrink a video file by lowering resolution and bitrate.",
    category: "media-tools",
    href: "/tools/media-tools/video-compressor",
    icon: "Minimize2",
    iconTint: "rose",
    popular: true,
    status: "ready",
    badge: "Media",
    keywords: ["compress video", "reduce video size", "smaller mp4"],
    longDescription: "Re-encode a short clip to a smaller file. Most browsers download WebM. Keep clips under 80 MB and 3 minutes.",
    faqs: [
      { question: "Is the video uploaded?", answer: "No. Compression runs on your device." },
      { question: "Why is the output WebM?", answer: "Browsers can record WebM reliably. MP4 encoding is only used when the browser supports it." },
    ],
  },
  {
    slug: "video-resizer",
    name: "Video Resizer",
    description: "Change a video’s width and height, including 1080p, 720p and 480p presets.",
    category: "media-tools",
    href: "/tools/media-tools/video-resizer",
    icon: "Scaling",
    iconTint: "blue",
    status: "ready",
    badge: "Media",
    keywords: ["resize video", "720p", "1080p", "scale video"],
  },
  {
    slug: "video-to-gif",
    name: "Video to GIF",
    description: "Turn the start of a video into an animated GIF.",
    category: "media-tools",
    href: "/tools/media-tools/video-to-gif",
    icon: "ImageDown",
    iconTint: "amber",
    status: "ready",
    badge: "Media",
    keywords: ["video to gif", "mp4 to gif", "make gif"],
    longDescription: "Sample frames from a short clip and build a GIF locally. Best for clips of a few seconds.",
  },
  {
    slug: "gif-to-video",
    name: "GIF to Video",
    description: "Convert an animated GIF into a video file.",
    category: "media-tools",
    href: "/tools/media-tools/gif-to-video",
    icon: "Film",
    iconTint: "purple",
    status: "ready",
    badge: "Media",
    keywords: ["gif to video", "gif to mp4", "gif to webm"],
  },
  {
    slug: "video-format-converter",
    name: "Video Format Converter",
    description: "Convert a clip to WebM or MP4.",
    category: "media-tools",
    href: "/tools/media-tools/video-format-converter",
    icon: "RefreshCcw",
    iconTint: "sky",
    status: "ready",
    badge: "Media",
    keywords: ["convert video", "mp4 webm", "video converter"],
  },
  {
    slug: "mp4-to-webm",
    name: "MP4 → WebM",
    description: "Convert an MP4 clip to WebM.",
    category: "media-tools",
    href: "/tools/media-tools/mp4-to-webm",
    icon: "Video",
    iconTint: "green",
    status: "ready",
    badge: "Media",
    keywords: ["mp4 to webm"],
  },
  {
    slug: "webm-to-mp4",
    name: "WebM → MP4",
    description: "Convert a WebM clip to MP4 when the browser can encode it.",
    category: "media-tools",
    href: "/tools/media-tools/webm-to-mp4",
    icon: "Video",
    iconTint: "indigo",
    status: "ready",
    badge: "Media",
    keywords: ["webm to mp4"],
    longDescription: "Re-encode WebM to MP4 locally. If the browser cannot record MP4, a local FFmpeg.wasm encoder is loaded on demand. Short clips work best.",
  },
  {
    slug: "video-fps-checker",
    name: "Video FPS Checker",
    description: "Measure how many frames per second a video plays at.",
    category: "media-tools",
    href: "/tools/media-tools/video-fps-checker",
    icon: "Gauge",
    iconTint: "orange",
    status: "ready",
    badge: "Media",
    keywords: ["video fps", "frame rate", "30fps 60fps"],
  },
  {
    slug: "video-metadata-viewer",
    name: "Video Metadata Viewer",
    description: "See duration, dimensions, file size and basic MP4 fields.",
    category: "media-tools",
    href: "/tools/media-tools/video-metadata-viewer",
    icon: "Info",
    iconTint: "teal",
    status: "ready",
    badge: "Media",
    keywords: ["video metadata", "video info", "duration resolution"],
  },
  ...extraTools,
];

export function getTool(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: CategoryId) {
  return tools.filter((tool) => tool.category === category);
}

export function getPopularTools() {
  return tools.filter((tool) => tool.popular);
}

export function getRelatedTools(tool: Tool, limit = 4) {
  return tools.filter((item) => item.slug !== tool.slug && item.category === tool.category).slice(0, limit);
}

export function searchTools(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return tools;
  return tools.filter((tool) => {
    const haystack = [tool.name, tool.description, tool.slug, ...tool.keywords].join(" ").toLowerCase();
    return haystack.includes(q);
  });
}

export function getCategoryToolCount(category: CategoryId) {
  const ready = getToolsByCategory(category).filter((tool) => tool.status === "ready").length;
  const categoryMeta = categories.find((item) => item.id === category);
  return { ready, label: categoryMeta?.countLabel ?? `${ready}+ tools` };
}
