import type { ReactNode } from "react";
import type { Tool } from "@/lib/types";
import { BmiCalculator } from "./BmiCalculator";
import {
  AgeCalculator,
  AverageCalculator,
  CalorieCalculator,
  DateCalculator,
  DiscountCalculator,
  FractionCalculator,
  InterestCalculator,
  LoanCalculator,
  PercentageCalculator,
  RatioCalculator,
  SalaryCalculator,
  TimeCalculator,
  TipCalculator,
} from "./EverydayCalculators";
import {
  AttendanceCalculator,
  CgpaCalculator,
  ExamCountdown,
  FinalGradeCalculator,
  GpaCalculator,
  GradeCalculator,
  MarksPercentageCalculator,
  StudyTimeCalculator,
  WeightedGradeCalculator,
} from "./StudentTools";
import {
  LengthConverter,
  TemperatureConverter,
  WeightConverter,
} from "./UtilityTools";
import {
  AcresToHectares,
  BarToPsi,
  BytesScale,
  CelsiusToFahrenheit,
  CmToFeet,
  CmToInches,
  CmToMm,
  FahrenheitToCelsius,
  FeetToCm,
  GigabytesToMegabytes,
  HectaresToAcres,
  HpToWatts,
  InchesToCm,
  KgToLbs,
  KgToStone,
  KmToMiles,
  KmhToMph,
  LbsToKg,
  LitersToGallons,
  MegabytesToGigabytes,
  MetersToFeet,
  MetersToYards,
  MilesToKm,
  MlToOz,
  MmToCm,
  MphToKmh,
  OzToMl,
  PsiToBar,
  StoneToKg,
  WattsToHp,
  YardsToMeters,
} from "@/components/converters/UnitConverters";
import {
  JpgToPdf,
  PdfToJpg,
  PdfToWord,
  TxtToPdf,
  WordToPdf,
} from "@/components/converters/DocumentConverters";
import {
  CsvToJson,
  JsonFormatter,
  JsonToCsv,
  JsonToYaml,
  XmlFormatter,
  XmlToJson,
  YamlToJson,
} from "@/components/converters/DataTools";
import {
  Base64Tool,
  HashGenerator,
  HtmlEntityEncoder,
  UnixTimestamp,
  UrlEncoder,
  UuidGenerator,
} from "@/components/converters/DeveloperTools";
import {
  ColorConverter,
  CssMinifier,
  HtmlFormatter,
  JsMinifier,
  JsonMinifier,
  JsonValidator,
  JwtDecoder,
  MarkdownToHtml,
  RegexTester,
  SqlFormatter,
} from "@/components/developers/DevExtras";
import {
  Base64ToImage,
  FaviconGenerator,
  ImageCompressor,
  ImageConverter,
  ImageCropper,
  ImageDimensionChecker,
  ImageFlipper,
  ImageMetadataViewer,
  ImageResizer,
  ImageRotator,
  ImageToBase64,
  JpgToPng,
  JpgToWebp,
  PngToJpg,
  PngToWebp,
  SvgToPng,
  WebpToJpg,
  WebpToPng,
} from "@/components/image/ImageTools";
import {
  ActiveToPassive,
  CaseConverter,
  CharacterCounter,
  FormalWritingConverter,
  GrammarChecker,
  ParagraphRewriter,
  ParaphrasingTool,
  PassiveToActive,
  ReadabilityChecker,
  RemoveDuplicateLines,
  SentenceRewriter,
  SentenceSimplifier,
  Summarizer,
  TextImprover,
  TextReverser,
  TextRewriter,
  WordCounter,
} from "@/components/writing/WritingTools";
import {
  GifToVideo,
  Mp4ToWebm,
  VideoCompressor,
  VideoFpsChecker,
  VideoFormatConverter,
  VideoMetadataViewer,
  VideoResizer,
  VideoToGif,
  WebmToMp4,
} from "@/components/media/MediaTools";
import { CompressPdf, MergePdf, PdfToText, RotatePdf, SplitPdf } from "@/components/converters/PdfExtras";
import {
  HeicToJpg,
  ImageBlur,
  ImageBorder,
  ImageGrayscale,
  ImageWatermark,
  OgImageResizer,
  PassportPhoto,
} from "@/components/image/ImageExtras";
import {
  FindAndReplace,
  LoremIpsum,
  MetaDescriptionCounter,
  RemoveExtraSpaces,
  SortLines,
  TextCompare,
} from "@/components/writing/TextExtras";
import {
  BoxShadowGenerator,
  ContrastChecker,
  CronExplainer,
  CssGradientGenerator,
  HtaccessGenerator,
  NumberBaseConverter,
  PasswordGenerator,
  QrCodeGenerator,
  RandomStringGenerator,
  RobotsTxtGenerator,
} from "@/components/developers/TrafficDev";
import {
  CgpaToPercentage,
  CompoundInterestCalculator,
  GstCalculator,
  IdealWeightCalculator,
  MortgageCalculator,
  OvulationCalculator,
  OvertimeCalculator,
  PaceCalculator,
  PercentageToGpa,
  PregnancyDueDate,
  ProteinCalculator,
  SipCalculator,
  SleepCalculator,
  TdeeCalculator,
  TimezoneConverter,
  WaterIntakeCalculator,
} from "@/components/calculators/TrafficCalculators";
import { ComingSoon } from "@/components/tools/ComingSoon";

const registry: Record<string, (tool: Tool) => ReactNode> = {
  "bmi-calculator": (tool) => <BmiCalculator tool={tool} />,
  "age-calculator": (tool) => <AgeCalculator tool={tool} />,
  "percentage-calculator": (tool) => <PercentageCalculator tool={tool} />,
  "discount-calculator": (tool) => <DiscountCalculator tool={tool} />,
  "tip-calculator": (tool) => <TipCalculator tool={tool} />,
  "loan-calculator": (tool) => <LoanCalculator tool={tool} />,
  "interest-calculator": (tool) => <InterestCalculator tool={tool} />,
  "date-calculator": (tool) => <DateCalculator tool={tool} />,
  "time-calculator": (tool) => <TimeCalculator tool={tool} />,
  "salary-calculator": (tool) => <SalaryCalculator tool={tool} />,
  "calorie-calculator": (tool) => <CalorieCalculator tool={tool} />,
  "average-calculator": (tool) => <AverageCalculator tool={tool} />,
  "ratio-calculator": (tool) => <RatioCalculator tool={tool} />,
  "fraction-calculator": (tool) => <FractionCalculator tool={tool} />,
  "gpa-calculator": (tool) => <GpaCalculator tool={tool} />,
  "cgpa-calculator": (tool) => <CgpaCalculator tool={tool} />,
  "attendance-calculator": (tool) => <AttendanceCalculator tool={tool} />,
  "grade-calculator": (tool) => <GradeCalculator tool={tool} />,
  "marks-percentage-calculator": (tool) => <MarksPercentageCalculator tool={tool} />,
  "final-grade-calculator": (tool) => <FinalGradeCalculator tool={tool} />,
  "weighted-grade-calculator": (tool) => <WeightedGradeCalculator tool={tool} />,
  "exam-countdown": (tool) => <ExamCountdown tool={tool} />,
  "study-time-calculator": (tool) => <StudyTimeCalculator tool={tool} />,
  "image-resizer": (tool) => <ImageResizer tool={tool} />,
  "image-compressor": (tool) => <ImageCompressor tool={tool} />,
  "image-cropper": (tool) => <ImageCropper tool={tool} />,
  "image-converter": (tool) => <ImageConverter tool={tool} />,
  "jpg-to-png": (tool) => <JpgToPng tool={tool} />,
  "png-to-jpg": (tool) => <PngToJpg tool={tool} />,
  "webp-to-jpg": (tool) => <WebpToJpg tool={tool} />,
  "jpg-to-webp": (tool) => <JpgToWebp tool={tool} />,
  "png-to-webp": (tool) => <PngToWebp tool={tool} />,
  "webp-to-png": (tool) => <WebpToPng tool={tool} />,
  "svg-to-png": (tool) => <SvgToPng tool={tool} />,
  "image-to-base64": (tool) => <ImageToBase64 tool={tool} />,
  "base64-to-image": (tool) => <Base64ToImage tool={tool} />,
  "image-rotator": (tool) => <ImageRotator tool={tool} />,
  "image-flipper": (tool) => <ImageFlipper tool={tool} />,
  "image-metadata-viewer": (tool) => <ImageMetadataViewer tool={tool} />,
  "favicon-generator": (tool) => <FaviconGenerator tool={tool} />,
  "image-dimension-checker": (tool) => <ImageDimensionChecker tool={tool} />,
  "json-formatter": (tool) => <JsonFormatter tool={tool} />,
  "json-to-csv": (tool) => <JsonToCsv tool={tool} />,
  "csv-to-json": (tool) => <CsvToJson tool={tool} />,
  "xml-to-json": (tool) => <XmlToJson tool={tool} />,
  "xml-formatter": (tool) => <XmlFormatter tool={tool} />,
  "yaml-to-json": (tool) => <YamlToJson tool={tool} />,
  "json-to-yaml": (tool) => <JsonToYaml tool={tool} />,
  "base64-encoder": (tool) => <Base64Tool tool={tool} lockedMode="encode" />,
  "base64-decoder": (tool) => <Base64Tool tool={tool} lockedMode="decode" />,
  "url-encoder": (tool) => <UrlEncoder tool={tool} lockedMode="encode" />,
  "url-decoder": (tool) => <UrlEncoder tool={tool} lockedMode="decode" />,
  "json-validator": (tool) => <JsonValidator tool={tool} />,
  "json-minifier": (tool) => <JsonMinifier tool={tool} />,
  "regex-tester": (tool) => <RegexTester tool={tool} />,
  "jwt-decoder": (tool) => <JwtDecoder tool={tool} />,
  "html-formatter": (tool) => <HtmlFormatter tool={tool} />,
  "css-minifier": (tool) => <CssMinifier tool={tool} />,
  "js-minifier": (tool) => <JsMinifier tool={tool} />,
  "sql-formatter": (tool) => <SqlFormatter tool={tool} />,
  "color-converter": (tool) => <ColorConverter tool={tool} />,
  "markdown-to-html": (tool) => <MarkdownToHtml tool={tool} />,
  "html-entity-encoder": (tool) => <HtmlEntityEncoder tool={tool} />,
  "unix-timestamp": (tool) => <UnixTimestamp tool={tool} />,
  "uuid-generator": (tool) => <UuidGenerator tool={tool} />,
  "hash-generator": (tool) => <HashGenerator tool={tool} />,
  "pdf-to-jpg": (tool) => <PdfToJpg tool={tool} />,
  "jpg-to-pdf": (tool) => <JpgToPdf tool={tool} />,
  "word-to-pdf": (tool) => <WordToPdf tool={tool} />,
  "pdf-to-word": (tool) => <PdfToWord tool={tool} />,
  "txt-to-pdf": (tool) => <TxtToPdf tool={tool} />,
  "video-compressor": (tool) => <VideoCompressor tool={tool} />,
  "video-resizer": (tool) => <VideoResizer tool={tool} />,
  "video-to-gif": (tool) => <VideoToGif tool={tool} />,
  "gif-to-video": (tool) => <GifToVideo tool={tool} />,
  "video-format-converter": (tool) => <VideoFormatConverter tool={tool} />,
  "mp4-to-webm": (tool) => <Mp4ToWebm tool={tool} />,
  "webm-to-mp4": (tool) => <WebmToMp4 tool={tool} />,
  "video-fps-checker": (tool) => <VideoFpsChecker tool={tool} />,
  "video-metadata-viewer": (tool) => <VideoMetadataViewer tool={tool} />,
  "word-counter": (tool) => <WordCounter tool={tool} />,
  "paraphrasing-tool": (tool) => <ParaphrasingTool tool={tool} />,
  "sentence-rewriter": (tool) => <SentenceRewriter tool={tool} />,
  "paragraph-rewriter": (tool) => <ParagraphRewriter tool={tool} />,
  "text-rewriter": (tool) => <TextRewriter tool={tool} />,
  "grammar-checker": (tool) => <GrammarChecker tool={tool} />,
  "sentence-simplifier": (tool) => <SentenceSimplifier tool={tool} />,
  "text-improver": (tool) => <TextImprover tool={tool} />,
  "formal-writing-converter": (tool) => <FormalWritingConverter tool={tool} />,
  "active-to-passive": (tool) => <ActiveToPassive tool={tool} />,
  "passive-to-active": (tool) => <PassiveToActive tool={tool} />,
  "summarizer": (tool) => <Summarizer tool={tool} />,
  "character-counter": (tool) => <CharacterCounter tool={tool} />,
  "case-converter": (tool) => <CaseConverter tool={tool} />,
  "remove-duplicate-lines": (tool) => <RemoveDuplicateLines tool={tool} />,
  "text-reverser": (tool) => <TextReverser tool={tool} />,
  "readability-checker": (tool) => <ReadabilityChecker tool={tool} />,
  "length-converter": (tool) => <LengthConverter tool={tool} />,
  "weight-converter": (tool) => <WeightConverter tool={tool} />,
  "temperature-converter": (tool) => <TemperatureConverter tool={tool} />,
  "kg-to-lbs": (tool) => <KgToLbs tool={tool} />,
  "lbs-to-kg": (tool) => <LbsToKg tool={tool} />,
  "cm-to-inches": (tool) => <CmToInches tool={tool} />,
  "cm-to-feet": (tool) => <CmToFeet tool={tool} />,
  "feet-to-cm": (tool) => <FeetToCm tool={tool} />,
  "km-to-miles": (tool) => <KmToMiles tool={tool} />,
  "miles-to-km": (tool) => <MilesToKm tool={tool} />,
  "celsius-to-fahrenheit": (tool) => <CelsiusToFahrenheit tool={tool} />,
  "fahrenheit-to-celsius": (tool) => <FahrenheitToCelsius tool={tool} />,
  "meters-to-feet": (tool) => <MetersToFeet tool={tool} />,
  "liters-to-gallons": (tool) => <LitersToGallons tool={tool} />,
  "inches-to-cm": (tool) => <InchesToCm tool={tool} />,
  "mb-to-gb": (tool) => <MegabytesToGigabytes tool={tool} />,
  "gb-to-mb": (tool) => <GigabytesToMegabytes tool={tool} />,
  "bytes-converter": (tool) => <BytesScale tool={tool} />,
  "mortgage-calculator": (tool) => <MortgageCalculator tool={tool} />,
  "gst-calculator": (tool) => <GstCalculator tool={tool} />,
  "timezone-converter": (tool) => <TimezoneConverter tool={tool} />,
  "sleep-calculator": (tool) => <SleepCalculator tool={tool} />,
  "pregnancy-due-date": (tool) => <PregnancyDueDate tool={tool} />,
  "ovulation-calculator": (tool) => <OvulationCalculator tool={tool} />,
  "tdee-calculator": (tool) => <TdeeCalculator tool={tool} />,
  "protein-calculator": (tool) => <ProteinCalculator tool={tool} />,
  "water-intake-calculator": (tool) => <WaterIntakeCalculator tool={tool} />,
  "ideal-weight-calculator": (tool) => <IdealWeightCalculator tool={tool} />,
  "compound-interest-calculator": (tool) => <CompoundInterestCalculator tool={tool} />,
  "overtime-calculator": (tool) => <OvertimeCalculator tool={tool} />,
  "pace-calculator": (tool) => <PaceCalculator tool={tool} />,
  "sip-calculator": (tool) => <SipCalculator tool={tool} />,
  "cgpa-to-percentage": (tool) => <CgpaToPercentage tool={tool} />,
  "percentage-to-gpa": (tool) => <PercentageToGpa tool={tool} />,
  "merge-pdf": (tool) => <MergePdf tool={tool} />,
  "split-pdf": (tool) => <SplitPdf tool={tool} />,
  "compress-pdf": (tool) => <CompressPdf tool={tool} />,
  "rotate-pdf": (tool) => <RotatePdf tool={tool} />,
  "pdf-to-text": (tool) => <PdfToText tool={tool} />,
  "images-to-pdf": (tool) => <JpgToPdf tool={tool} />,
  "heic-to-jpg": (tool) => <HeicToJpg tool={tool} />,
  "image-watermark": (tool) => <ImageWatermark tool={tool} />,
  "passport-photo": (tool) => <PassportPhoto tool={tool} />,
  "image-grayscale": (tool) => <ImageGrayscale tool={tool} />,
  "image-blur": (tool) => <ImageBlur tool={tool} />,
  "image-border": (tool) => <ImageBorder tool={tool} />,
  "og-image-resizer": (tool) => <OgImageResizer tool={tool} />,
  "mph-to-kmh": (tool) => <MphToKmh tool={tool} />,
  "kmh-to-mph": (tool) => <KmhToMph tool={tool} />,
  "stone-to-kg": (tool) => <StoneToKg tool={tool} />,
  "kg-to-stone": (tool) => <KgToStone tool={tool} />,
  "oz-to-ml": (tool) => <OzToMl tool={tool} />,
  "ml-to-oz": (tool) => <MlToOz tool={tool} />,
  "psi-to-bar": (tool) => <PsiToBar tool={tool} />,
  "bar-to-psi": (tool) => <BarToPsi tool={tool} />,
  "watts-to-hp": (tool) => <WattsToHp tool={tool} />,
  "hp-to-watts": (tool) => <HpToWatts tool={tool} />,
  "acres-to-hectares": (tool) => <AcresToHectares tool={tool} />,
  "hectares-to-acres": (tool) => <HectaresToAcres tool={tool} />,
  "cm-to-mm": (tool) => <CmToMm tool={tool} />,
  "mm-to-cm": (tool) => <MmToCm tool={tool} />,
  "yards-to-meters": (tool) => <YardsToMeters tool={tool} />,
  "meters-to-yards": (tool) => <MetersToYards tool={tool} />,
  "remove-extra-spaces": (tool) => <RemoveExtraSpaces tool={tool} />,
  "find-and-replace": (tool) => <FindAndReplace tool={tool} />,
  "sort-lines": (tool) => <SortLines tool={tool} />,
  "lorem-ipsum": (tool) => <LoremIpsum tool={tool} />,
  "text-compare": (tool) => <TextCompare tool={tool} />,
  "meta-description-counter": (tool) => <MetaDescriptionCounter tool={tool} />,
  "qr-code-generator": (tool) => <QrCodeGenerator tool={tool} />,
  "password-generator": (tool) => <PasswordGenerator tool={tool} />,
  "cron-explainer": (tool) => <CronExplainer tool={tool} />,
  "htaccess-generator": (tool) => <HtaccessGenerator tool={tool} />,
  "robots-txt-generator": (tool) => <RobotsTxtGenerator tool={tool} />,
  "css-gradient-generator": (tool) => <CssGradientGenerator tool={tool} />,
  "box-shadow-generator": (tool) => <BoxShadowGenerator tool={tool} />,
  "random-string-generator": (tool) => <RandomStringGenerator tool={tool} />,
  "contrast-checker": (tool) => <ContrastChecker tool={tool} />,
  "number-base-converter": (tool) => <NumberBaseConverter tool={tool} />,
};

export function renderTool(tool: Tool) {
  if (tool.status === "soon") return <ComingSoon tool={tool} />;
  const view = registry[tool.slug];
  return view ? view(tool) : <ComingSoon tool={tool} />;
}
